### ISSUE TITLE
Improve Responsiveness

### ISSUE THREAD

**Issue by Mahich123** [Mahich123/Image_Search#18]
Our site being updated slowly . We are taking time to build it as we want to make it stable . 
Help us to improve the responsiveness of our site . 
Every contribution means to us 😀

**Comment by abitsalihu** [comment]
Hey @Mahich123 , I would like to help on this issue. :)

**Comment by Mahich123** [comment]
## Great!! 
Assigning you to this issue .
You can join our [Discord](https://discord.gg/uTpGAThYG8) server also

**Comment by Mahich123** [comment]
@abitsalihu  Are you working on this one ? 
Let us know the progress.

**Comment by abitsalihu** [comment]
@Mahich123 yes, I will make a PR later today :)

**Comment by Mahich123** [comment]
Great!! 
No rush take your time. I was just checking.

**Comment by abitsalihu** [comment]
@Mahich123 hey man, the website is fully responsive as I'm viewing it right now, @media queries were included 2 days ago.

Honestly I don't think there is anything I can improve as it is fully responsive.

Only if you want me to find some kind of small mistakes and fix those?

**Comment by Mahich123** [comment]
@abitsalihu  For some viewports carousel and genre part are breaking . Check is there any way to improve it. 
![image](https://user-images.githubusercontent.com/69717681/190635627-4527c977-fc30-436e-a350-2d7bbf6720a1.png)

**Comment by abitsalihu** [comment]
@Mahich123 I'll check for this and any other stuff that needs fixing. :)

**Comment by Mahich123** [comment]
For now, everything is OK.
