### ISSUE TITLE
Contribute to search result page 

### ISSUE THREAD

**Issue by Mahich123** [Mahich123/Image_Search#25]
Search result page Design has been created. If anyone comes to this issue you can contribute on creating that page .

**Comment by andrewkykoo** [comment]
Hi @Mahich123, I would like to help with the search result page. Could you share more details/specifications you are envisioning? Thanks.

**Comment by Mahich123** [comment]
@andrewkykoo  You can find the design here . Design is at section 9 you can work on whichever parts you want to you dont have to do all the parts .
You can join our server if you wish to
https://discord.com/invite/eKrezHzEZH
 If need any help let me know . 
 
Figma : 
https://www.figma.com/file/QTeCalCfh3gqLNoWnVx4jG/ImageSearch?node-id=0%3A1

**Comment by Mahich123** [comment]
@andrewkykoo  Any updates on it ?
