### ISSUE TITLE
Contribute on creating site layout

### ISSUE THREAD

**Issue by Mahich123** [Mahich123/Image_Search#7]

**Comment by Sam-Takahashi** [comment]
I'll look into this during my spare time. Can you provide more context?

**Comment by Mahich123** [comment]
Our site is not properly designed yet .
This issue is for the coding part helping in making the site from design . 
@Sam-Takahashi

**Comment by Sam-Takahashi** [comment]
I see. Do you have a general wireframe for the page(s)? Or are you starting completely from scratch?

**Comment by Mahich123** [comment]
we starting from scratch info given in discord
